# Generated by Django 3.1.3 on 2020-12-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisory_commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('photo_desktop', models.ImageField(blank=True, null=True, upload_to='images/desktop', verbose_name='photo desktop')),
                ('photo_mobile', models.ImageField(blank=True, null=True, upload_to='images/mobile', verbose_name='photo mobile')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='events', to='advisory_commons.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
