# Generated by Django 3.1.3 on 2020-11-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisory_team', '0001_initial'),
        ('advisory_commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='content')),
                ('photo_desktop', models.ImageField(blank=True, null=True, upload_to='images/desktop', verbose_name='photo desktop')),
                ('photo_mobile', models.ImageField(blank=True, null=True, upload_to='images/mobile', verbose_name='photo mobile')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('team_members', models.ManyToManyField(related_name='departments', to='advisory_team.TeamMember', verbose_name='team members')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='content')),
                ('photo_desktop', models.ImageField(blank=True, null=True, upload_to='images/desktop', verbose_name='photo desktop')),
                ('photo_mobile', models.ImageField(blank=True, null=True, upload_to='images/mobile', verbose_name='photo mobile')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='advisory_services.department', verbose_name='department')),
                ('tags', models.ManyToManyField(related_name='services', to='advisory_commons.Tag', verbose_name='tags')),
                ('team_members', models.ManyToManyField(related_name='services', to='advisory_team.TeamMember', verbose_name='team members')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
